### ISSUE TITLE
Bag addon I made to go with NeavUI.

### ISSUE THREAD

**Issue by Grimsbain** [renstrom/NeavUI#112]
I made a little addon that lets you toggle your bags via a keybind. The keybind can be set in game and the icons include !Beautycase borders so it looks a little cleaner and fits in with the rest of the UI. If you are interested fell free to add it to the UI.

http://imgur.com/JVfF6LH

https://github.com/Grimsbain/nBags

PS: All the code works on live you would just need to change the ToC and remove the code in nMainbar\modules\short\short.lua since it hides the bags. Just comment out or delete line 37 and 40-43.

**Comment by Grimsbain** [comment]
@renstrom I could always just integrate this into nMainbar if you are interested. Here is a quick video of it in action.

https://youtu.be/EASp12m_GzQ

**Comment by renstrom** [comment]
You didn't need to close this. I just haven't gotten around to it. I have vacation, so that's why things are slow :)

**Comment by renstrom** [comment]
@Grimsbain you can add it to nMainbar
