### ISSUE TITLE
A bunch of errors in the new version

### ISSUE THREAD

**Issue by Andersbbrandt** [renstrom/NeavUI#127]
Message: Interface\AddOns\nCore\modules\errors.lua:7: table index is nil
Time: 06/27/16 15:19:14
Count: 1
Stack: Interface\AddOns\nCore\modules\errors.lua:7: in main chunk

Locals: (*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 0.75
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"

**Comment by Andersbbrandt** [comment]
Message: Interface\AddOns\nMainbar\modules\repbar.lua:7: attempt to index field 'OverlayFrame' (a nil value)
Time: 06/27/16 15:24:46
Count: 1
Stack: Interface\AddOns\nMainbar\modules\repbar.lua:7: in main chunk

Locals: _ = "nMainbar"
nMainbar = <table> {
 Config = <table> {
 }
}
cfg = <table> {
 multiBarRight = <table> {
 }
 multiBarBottomRight = <table> {
 }
 honorBar = <table> {
 }
 MainMenuBar = <table> {
 }
 color = <table> {
 }
 multiBarLeft = <table> {
 }
 multiBarBottomLeft = <table> {
 }
 showPicomenu = true
 artifactBar = <table> {
 }
 vehicleBar = <table> {
 }
 expBar = <table> {
 }
 possessBar = <table> {
 }
 button = <table> {
 }
 stanceBar = <table> {
 }
 petBar = <table> {
 }
 repBar = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'OverlayFrame' (a nil value)"

**Comment by Andersbbrandt** [comment]
Message: Interface\AddOns\nMainbar\modules\artifactBar.lua:7: attempt to index global 'ArtifactWatchBar' (a nil value)
Time: 06/27/16 15:24:46
Count: 1
Stack: Interface\AddOns\nMainbar\modules\artifactBar.lua:7: in main chunk

Locals: _ = "nMainbar"
nMainbar = <table> {
 Config = <table> {
 }
}
cfg = <table> {
 multiBarRight = <table> {
 }
 multiBarBottomRight = <table> {
 }
 honorBar = <table> {
 }
 MainMenuBar = <table> {
 }
 color = <table> {
 }
 multiBarLeft = <table> {
 }
 multiBarBottomLeft = <table> {
 }
 showPicomenu = true
 artifactBar = <table> {
 }
 vehicleBar = <table> {
 }
 expBar = <table> {
 }
 possessBar = <table> {
 }
 button = <table> {
 }
 stanceBar = <table> {
 }
 petBar = <table> {
 }
 repBar = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArtifactWatchBar' (a nil value)"

**Comment by Andersbbrandt** [comment]
Message: Interface\AddOns\oUF_Neav\castbar.lua:53: attempt to call method 'SetColorTexture' (a nil value)
Time: 06/27/16 15:24:46
Count: 1
Stack: Interface\AddOns\oUF_Neav\castbar.lua:53: in function `CreateCastbars'
Interface\AddOns\oUF_Neav\core.lua:466: in function `styleFunc'
Interface\AddOns\oUF\ouf.lua:262: in function <Interface\AddOns\oUF\ouf.lua:192>
(tail call): ?
Interface\AddOns\oUF\ouf.lua:555: in function `Spawn'
Interface\AddOns\oUF_Neav\core.lua:1364: in function `func'
Interface\AddOns\oUF\factory.lua:20: in function <Interface\AddOns\oUF\factory.lua:16>
(tail call): ?

Locals: self = oUF_Neav_Player {
 IsMainFrame = true
 Castbar = oUF_Neav_PlayerCastbar {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\oUF\ouf.lua:149
 unit = "player"
 menu = <function> defined @Interface\AddOns\oUF_Neav\core.lua:24
 style = "oUF_Neav"
 IsTargetFrame = false
 0 = <userdata>
 UNIT_EXITED_VEHICLE = <function> defined @Interface\AddOns\oUF\ouf.lua:38
 __elements = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\oUF\ouf.lua:38
}
unit = "player"
config = <table> {
 scale = 0.93
 safezoneColor = <table> {
 }
 width = 220
 show = true
 color = <table> {
 }
 showSafezone = true
 position = <table> {
 }
 height = 19
 classcolor = true
 icon = <table> {
 }
 showLatency = true
}
playerColor = <table> {
 b = 0.41
 colorStr = "fffff569"
 g = 0.96
 r = 1
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 1
(*temporary) = 0
(*temporary) = 1
(*temporary) = "attempt to call method 'SetColorTexture' (a nil value)"
ns = <table> {
 ColorBorder = <function> defined @Interface\AddOns\oUF_Neav\func\castbar.lua:5
 UpdateAuraIcons = <function> defined @Interface\AddOns\oUF_Neav\func\aura.lua:101
 UpdateAuraTimer = <function> defined @Interface\AddOns\oUF_Neav\func\aura.lua:21
 CustomDelayText = <function> defined @Interface\AddOns\oUF_Neav\func\castbar.lua:15
 PortraitTimerDB = <table> {
 }
 CustomTimeText = <function> defined @Interface\AddOns\oUF_Neav\func\castbar.lua:11
 utf8sub = <function> defined @Interface\AddOns\oUF_Neav\func\func.lua:165
 PostUpdateIcon = <function> defined @Interface\AddOns\oUF_Neav\func\aura.lua:47
 GetPowerText = <function> defined @Interface\AddOns\oUF_Neav\func\func.lua:121
 StopFlash = <function> defined @Interface\AddOns\oUF_Neav\func\flash.lua:50
 CreateCastbars = <function> defined @Interface\AddOns\oUF_Neav\castbar.lua:22
 CreateCastbarStrings = <function> defined @Interface\AddOns\oUF_Neav\func\castbar.lua:19
 FormatTime = <function> defined @Interface\AddOns\oUF_Neav\func\func.lua:52
 IsFlashing = <function> defined @Interface\AddOns\oUF_Neav\func\flash.lua:40
 StartFlash = <function> defined @Interface\AddOns\oUF_Neav\func\flash.lua:56
 cUnit = <function> defined @Interface\AddOns\oUF_Neav\func\func.lua:36
 MultiCheck = <function> defined @Interface\AddOns\oUF_Neav\func\func.lua:155
 Config = <table> {
 }
 GetHealthText = <function> defined @Interface\AddOns\oUF_Neav\func\func.lua:95
}
UpdateCastbarColor = <function> defined @Interface\AddOns\oUF_Neav\castbar.lua:4

**Comment by Andersbbrandt** [comment]
Message: Interface\AddOns\!Colorz\!Colorz.lua:20: attempt to call global 'UnitIsTapDenied' (a nil value)
Time: 06/27/16 15:24:46
Count: 14
Stack: Interface\AddOns\!Colorz\!Colorz.lua:20: in function `UnitSelectionColor'
Interface\FrameXML\TargetFrame.lua:326: in function `TargetFrame_CheckFaction'
Interface\FrameXML\TargetFrame.lua:194: in function `OnEvent'
Interface\FrameXML\UnitFrame.lua:676: in function <Interface\FrameXML\UnitFrame.lua:674>

Locals: unit = "boss5"
r = nil
g = nil
b = nil
(*temporary) = nil
(*temporary) = "boss5"
(*temporary) = "attempt to call global 'UnitIsTapDenied' (a nil value)"

**Comment by Andersbbrandt** [comment]
Seems a lot of the UI breaks because of those temporary variables

**Comment by Kkthnx** [comment]
@Andersbbrandt Are you currently trying to use this version on live servers because this is being brought up-to-date for Legion currently.?

**Comment by Andersbbrandt** [comment]
@Kkthnx yeah, I just came back to play a bit of WoW and updated my UI without checking the version, my apologies. Downgrading worked fine.
