### ISSUE TITLE
Player/Target Dropdown Focus Error

### ISSUE THREAD

**Issue by Grimsbain** [renstrom/NeavUI#150]
Using the focus option in the dropdown menus for the player and target frame causes Blizzard to block the action. This isn't unique to our code or to oUF but the problem has been around for so long that it isn't likely to be fixed. So we have two options either we stay with what we have or let Blizzard handle all of the menus and replace the custom lock/unlock/reset position menu we have with slash commands.

I have all the code written and working but I wanted to ask what you thought before submitting it. We would have two slash commands one called /neavlock that would unlock the player, target, and focus frames all at the same time and /neavreset with options to reset all or by frame name.

**Comment by Grimsbain** [comment]
We could also add the lock/unlock options to the picomenu in nMainbar.

**Comment by Grimsbain** [comment]
Here is a video of it in action.

https://youtu.be/wxDRmofp-N8

**Comment by renstrom** [comment]
It's a shame this is the case (stupid taint issues!). But we probably don't have much choice but to go down this road. One thing though, I wonder if we should add modifiers for moving the frames, similar to the pet-/stance bar for example. Then you have to press alt+shift to drag, that way it can more or less be unlocked all the time.

**Comment by renstrom** [comment]
https://github.com/renstrom/NeavUI/pull/169
