### ISSUE TITLE
nCore _bubbles.lua?

### ISSUE THREAD

**Issue by Grimsbain** [renstrom/NeavUI#151]
Was bubbles.lua in nCore disabled for a reason? In the ToC it just calls bubbles.lua but the name of the file is _bubbles.lua.

**Comment by Kkthnx** [comment]
@Neav You can use these I coded up.
https://github.com/Kkthnx/NeavUI_Legion/blob/master/Interface/AddOns/nCore/modules/bubbles.lua

preview here 
https://www.youtube.com/watch?v=ye7Stxpq0EE

**Comment by renstrom** [comment]
@Kkthnx is you version working and bug free?

**Comment by Kkthnx** [comment]
The chat bubble script is, yes. Repo of your UI no on my end locally and on GitHub fork. I haven't caught up with the latest changes.
