### ISSUE TITLE
Legion Beta: Combopoints not updated

### ISSUE THREAD

**Issue by daneras** [renstrom/NeavUI#168]
Hello,

First: i love your UI and use it since years and want to thank you for the time of codeing.

### Issue
If your oUF_Neav is used in Legion Beta, the Combopoints on the target are not shown until you deselect the target und select it again. Then u get the actual combos, but no update if u use it or put another ones to.

Maybe it could be because oUF is not updated to Legion Beta?

### Nice to have
If you could add the extra combos from the talent "Anticipation" it would be very cool (don't use the Powerbar).

### Version
WoW Version: 7.0.3.22217 from today (also with pre versions)
WoW Platforms: testet on Beta and PTR, same result (on live it works)

If you have any questions or want a tester for the bugfix, just let me know.

Thank you and greetings,
Daneras

**Comment by renstrom** [comment]
>Maybe it could be because oUF is not updated to Legion Beta?

Might related to https://github.com/haste/oUF/pull/272 and/or https://github.com/haste/oUF/pull/266.

**Comment by daneras** [comment]
Thx for the answer. Would try this. Hopefully it will come a new version of oUF.

**Comment by Grimsbain** [comment]
It is a very minor change in the oUF code. All you need to do is add the UNIT_POWER_FREQUENT event in  the Enable and Disable functions. I would have said so before but I have been busy moving.

**Comment by L3n1n** [comment]
Combopoints not updated too in nPower.

**Comment by renstrom** [comment]
@L3n1n nPower is gone, see https://github.com/renstrom/NeavUI/pull/147

**Comment by L3n1n** [comment]
@renstrom I am very disappointed, because I used this addon about 3 years :(

**Comment by renstrom** [comment]
We decided that the new class resource bar introduced in Legion basically does everything nPower did, and more. What are you missing from nPower that isn't provided by the new resource bar?

**Comment by L3n1n** [comment]
- New resource bar a little floats across the screen
- I do not like its design

**Comment by renstrom** [comment]
I see, I guess that's fair. I'll see if there's anything I can do, not making any promises though. Might just be a reskinned version of the default resource bar.

By the way, have you tried [NugComboBar](http://www.wowinterface.com/downloads/info6308-NugComboBar.html)?

**Comment by L3n1n** [comment]
reskinned version - good decision, I think
NugComboBar - I used this addon 5 years ago and its design is disgusting

I found an alternative solution and set up a group in WeakAuras 2 (bottom nPower)

![](http://i.imgur.com/WDEkLIw.jpg)

**Comment by Grimsbain** [comment]
@L3n1n I updated nPower for anyone that really wants it. It won't show the buff icons (that is too much work) but it should work for all classes now. Because of some changes the number above the bar is always in a static position but that isn't that big of a deal. #180

**Comment by L3n1n** [comment]
@Grimsbain omg it's amazing, I appreciate it!
But I can found little bug with SetScale - this option does not work for all elements.

**Comment by Grimsbain** [comment]
@L3n1n I just pushed out an update. I fixed the bug and added a scale option to the config file to make it easier for people to change its size.

**Comment by L3n1n** [comment]
@Grimsbain thank you very much, works great! :heart:

Maybe I'm asking a lot, but is it possible to make colored numbers of class resources? For example, a rogue can be a maximum combo points of 5, 6 or 8 depending on the selected talent; for monk at 4 or 5 and etc. Previously, it was very comfortable see the visual transition colors: white - yellow - red.

**Comment by Grimsbain** [comment]
@L3n1n Done, works for combo points, chi, arcane charges, holy power, and soul shards. Will show max as red, max-1 as yellow, and all else as white.

**Comment by L3n1n** [comment]
@Grimsbain thank you so much! Now I'm ready for Legion.

**Comment by renstrom** [comment]
@daneras is this still an issue?

**Comment by daneras** [comment]
Nope, everything fine now with the new oUF_Neav in combination with oUF from LS. No bugs here anymore. Thx @ all.
