### ISSUE TITLE
oUF Legion

### ISSUE THREAD

**Issue by Grimsbain** [renstrom/NeavUI#170]
If anyone is looking for a good version of oUF for Legion I suggest getting the version from ls. He has pulled in his updates and the ones from p3lim. You can get it here.

https://github.com/ls-/oUF

**Comment by renstrom** [comment]
I should probably change our oUF dependency to that until everything is merged upstream.

**Comment by renstrom** [comment]
I just changeed to ls-/oUF (for now) https://github.com/renstrom/NeavUI/commit/72fced058a3458c0a17477545807f4bb2c82b0a6
