### ISSUE TITLE
DruidMana in Legion

### ISSUE THREAD

**Issue by Grimsbain** [renstrom/NeavUI#171]
@renstrom Some of the recent updates for oUF have DruidMana and PowerPrediction have the code check the `ALT_MANA_BAR_PAIR_DISPLAY_INFO` table to see if they should be shown. Blizzard no longer shows the mana bar when Druids are in bear and cat form so we can either do the same or override the table with a custom version.

```
ALT_MANA_BAR_PAIR_DISPLAY_INFO = {
	DRUID = {
		[SPELL_POWER_LUNAR_POWER] = true,
        [SPELL_POWER_ENERGY] = true,
        [SPELL_POWER_RAGE] = true,
	},
	PRIEST = {
		[SPELL_POWER_INSANITY] = true,
	},
	SHAMAN = {
		[SPELL_POWER_MAELSTROM] = true,
	},
}
```
What would you prefer?

**Comment by renstrom** [comment]
Good question. On one hand I would like to stay as close to the default Blizzard behaviour as possible. One the other hand I can see usefulness in being able to see mana at all times, but perhaps it's not as important as before? Like shifting for a quick heal in PvP or whatever.

I say we go for the Blizzard behaviour, and if it turns there's a demand to be able to see mana in cat/bear form we can change it later.

**Comment by Grimsbain** [comment]
If we are going to do this we could also drop the old way of doing combo points or at least have an option to use the new `ComboPointPlayerFrame`. It shows the combo points on the user frame instead of the target frame. The only downside is that any vehicle that uses combo points (not very common) won't be displayed (the default UI isn't showing them either).

**Comment by renstrom** [comment]
Well if that's what the default UI is doing, then I say go for it! :)
