### ISSUE TITLE
Bossframe not moveable

### ISSUE THREAD

**Issue by daneras** [renstrom/NeavUI#181]
Hi,

i have yesterday fighted to Archimonde in LFR an wanted to move the Bossframe von the bottom left corner. ALT+SHIFT and drag does not work as also the numbers in the config.lua doesn't work.

Is there any other way to move or is this a bug?

Greets,
Daneras

**Comment by renstrom** [comment]
Hm, alt+shift moving isn't enabled for the boss frames (but maybe we should add it?). But if the changing the position in `config.lua` isn't working, then it's likely a bug!

**Comment by daneras** [comment]
ok, i changed the position to TOP an changed the numbers, other things i left original. At reload, it don't worket.
It would be very cool if you can add the alt+shift option. this is awesome.

**Comment by Grimsbain** [comment]
Added movable boss and arena frames to #180.

**Comment by daneras** [comment]
I have added your code now an reloaded ingame. Got the following error:

Message: Interface\AddOns\oUF_Neav\core.lua:1349: '<eof>' expected near 'end'
Time: 07/21/16 23:09:16
Count: 1
Stack: 
Locals:

**Comment by daneras** [comment]
Uploaded here my 2 files, maybe i make a mistake.

[oUF_Neav.zip](https://github.com/renstrom/NeavUI/files/377003/oUF_Neav.zip)

**Comment by Grimsbain** [comment]
At line 1131 you should have `if (not config.units[ns.cUnit(unit)].disableAura) then` above `if (config.units.target.showDebuffsOnTop) then`.

**Comment by daneras** [comment]
Many thx, work fine now, you guys are awesome!

**Comment by daneras** [comment]
Can't test Bossframes now, but i have no errors, think it will work fine.
