### ISSUE TITLE
Garrison message at bottom screen

### ISSUE THREAD

**Issue by daneras** [renstrom/NeavUI#182]
Sorry for posting this here, i can't make a Pull Request.

Is there any opportunity that you can add in the nCore an Option to hide the Garrison "ready mission" messages or move it to the TOP of the screen?
This would be VERY COOL :)

Greets, Daneras

**Comment by renstrom** [comment]
Hmm, is this something new in Legion? I'm not sure I know what the "ready mission" messages are, perhaps a screenshot?

**Comment by daneras** [comment]
Ok, i thought i couldn't write that correct ;). Just add a Screenshot.
As option:
Hide
Move to top (as ElvUI does f.e.)

I don't want to use an extra addon for this.
![garrison-screen](https://cloud.githubusercontent.com/assets/20454019/17015378/2bdec56a-4f2a-11e6-956a-66dc18f570d8.jpg)

**Comment by renstrom** [comment]
Oh, *that* one :) Yes I guess that can be added! :)

**Comment by daneras** [comment]
cool, would be awesome :)

**Comment by Grimsbain** [comment]
Done, added code to nCore. It will move any alert like that to the top of the screen. #180

**Comment by daneras** [comment]
Many thx, worked fine.
/closed
