### ISSUE TITLE
oUF_Neav: Targetframe debuffs

### ISSUE THREAD

**Issue by daneras** [renstrom/NeavUI#183]
Hi again (sorry for the many reports),

are the following two options possible? (I have nothing found in the config or via rightclick on the target)

1. Show only my debuffs (was a standard setting in the Blizzard UI, nothing there yet, they have killed it)
2. Put the debuffs on top of the target frame as in the screenshot shown

Only if it's easy possible :)

![ouf-neav-targetframe](https://cloud.githubusercontent.com/assets/20454019/17016680/7e3e5d4c-4f30-11e6-98b0-1a6b925c1c3a.jpg)

**Comment by Grimsbain** [comment]
Done, added to pull request. #180

**Comment by daneras** [comment]
Very cool, many thx to you guys!

**Comment by daneras** [comment]
Work fine now!
