### ISSUE TITLE
Autosell grey and Autorepair

### ISSUE THREAD

**Issue by daneras** [renstrom/NeavUI#184]
Hi Guys, i'm again ;)

is it possible to add Autorepair (from Player Gold) and autosell grey items to nCore?
Would be very nice :)

Greets, Daneras.

**Comment by renstrom** [comment]
Hmm.. Honestly, I'm a bit reluctant about adding this. I'd rather not give in to feature creep for stuff that the addon community already provides via single-purpose addons like [AutoSellGreyRepair](http://www.wowinterface.com/downloads/info23769-AutoSellGreyRepair.html) or [SellGreyRepair](http://www.wowinterface.com/downloads/info22101-SellGreyRepair.html). Or even my own [prButler](https://github.com/renstrom/prButler) for that matter. Especially for something that isn't an aesthetic change (like moving the alert frame).

**Comment by daneras** [comment]
Ok, thx for that. I'll use one of the other addons. :)
