### ISSUE TITLE
Player marker in minimap

### ISSUE THREAD

**Issue by frankallen** [renstrom/NeavUI#188]
hello,

the player marker (arrow) isn't in the middle of the minimap, its on top/right:
http://i.imgur.com/rI8d0Q3.png

insteat of the arrow it's a grey circle.

**Comment by Grimsbain** [comment]
This isn't related to nMinimap. I'm not sure what is wrong but I have seen multiple reports on live and in beta of people having issues with the minimap.

**Comment by Grimsbain** [comment]
Has anyone using the current version of nMinimap ran into this problem again?

**Comment by frankallen** [comment]
Can confirm, since ~1 week the problem is gone.

**Comment by renstrom** [comment]
Great!
