### ISSUE TITLE
Buffs frame on top of the LFG tooltip

### ISSUE THREAD

**Issue by L3n1n** [renstrom/NeavUI#189]
This bug only for me?

![](http://i.imgur.com/Z2Uh5Xw.jpg)

**Comment by Grimsbain** [comment]
I have no idea why this is happening. The buffs frames are set to the the low strata and that frame is set to the tooltip strata (the highest strata) but it is still showing up below other objects.

**Comment by Kkthnx** [comment]
This could be an issue on Blizzards side.

**Comment by Grimsbain** [comment]
@renstrom I have looked into this and the bug was fixed a month after this was posted so this can be removed now.

**Comment by renstrom** [comment]
Great! Closing then.
