### ISSUE TITLE
Statusbar texture for power showing outside of frame

### ISSUE THREAD

**Issue by notnexi** [renstrom/NeavUI#195]
At 0 rage: https://i.imgur.com/zd7fGkG.png
Near full rage: https://i.imgur.com/DB2wrWe.png
The texture shifts to the right as I gain more rage.

Issue seems to be the same for Mana as well
At low mana: https://i.imgur.com/ZZcuZ6q.png
Full mana: https://i.imgur.com/TaTtM2Z.png

Also happens on party frames.

Using latest NeavUI from Github, no other addon enabled.

**Comment by Grimsbain** [comment]
Are you using the version of oUF that we provide? The oUF from haste still hasn't been updated yet.

**Comment by notnexi** [comment]
That would be why, it wasn't included in the git download.
Issue "resolved", cheers.
