### ISSUE TITLE
Raidframes sorting

### ISSUE THREAD

**Issue by frankallen** [renstrom/NeavUI#200]
hello supporters

got a question about the raidframes:
http://i.imgur.com/H41GEjZ.png

why is group 3 not filled with 1 player? :S

**Comment by Grimsbain** [comment]
The raid frames are automatically generated by Blizzards group header api and it is setup to group by group but it will auto fill any missing spots. The only way this could be fixed is to create each group separately.

**Comment by frankallen** [comment]
But this is new, right?

**Comment by renstrom** [comment]
If I'm not mistaken the change in behaviour was introduced in this commit https://github.com/renstrom/NeavUI/commit/e2ec098575edd79e53cb163a1ab947c181724616#diff-5b837a2c8faa432affe723431bdac7a2

**Comment by renstrom** [comment]
Fixed in https://github.com/renstrom/NeavUI/pull/232
