### ISSUE TITLE
Alert frames are stacking in the wrong direction

### ISSUE THREAD

**Issue by renstrom** [renstrom/NeavUI#208]
This causes alerts besides the first one to appear off screen.

![](https://puu.sh/qXqdq/2c5ff47545.jpg)

**Comment by Grimsbain** [comment]
Sadly we don't have an easy fix for this. I would suggest anyone that wants to move the frames to download [ls; Toasts](http://www.wowinterface.com/downloads/info24123-lsToasts.html). It does a much better job than we could.

**Comment by renstrom** [comment]
Yes, that's what I'm currently doing. So I guess we either just delete `alertframemover.lua` and refer to something like [ls: Toasts](http://www.wowinterface.com/downloads/info24123-lsToasts.html) if someone wants to customize this. Or we try and fix ourselves, [this](https://github.com/Shestak/ShestakUI/blob/master/ShestakUI/Modules/Blizzard/AlertFrames.lua) might be a good starting point?

I'm actually leaning towards the former...
