### ISSUE TITLE
nTooltip bug - world quests

### ISSUE THREAD

**Issue by L3n1n** [renstrom/NeavUI#210]
Border bug - only if reward for world quest will be any item, not gold or resources.

![](http://i.imgur.com/KF81kuY.jpg)

**Comment by Kkthnx** [comment]
Need to add Worldmap.backdrop to the list of tooltips I think to fix this @Grimsbain @renstrom ??

**Comment by Grimsbain** [comment]
Looks like replacing WorldMapTooltip with WorldMapTooltip.BackdropFrame fixes this problem.

**Comment by renstrom** [comment]
Fixed in https://github.com/renstrom/NeavUI/pull/211
