### ISSUE TITLE
nTooltip error

### ISSUE THREAD

**Issue by Likusmydikus** [renstrom/NeavUI#213]
371x nTooltip\health-Health.lua:84: <unnamed>:SetText(): Font not set
[C]: in function `SetText'
nTooltip\health-Health.lua:84: in function <nTooltip\health.lua:82>
[C]: ?

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = ""

Can someone help me? Thank you.

**Comment by Grimsbain** [comment]
Does your config.lua file still have `font = 'Fonts\\ARIALN.ttf',` under healthbar?

**Comment by Technojo01** [comment]
Also, even with the latest github code, Worldquest does not skin well.

https://i.imgur.com/NH5ERUk.png

**Comment by Grimsbain** [comment]
Are you sure you are using the newest version? Because I haven't had any issues since we fixed it.

**Comment by Technojo01** [comment]
Scratch that, went ahead and merged config but forget to merge core.lua >< sorry...
