### ISSUE TITLE
nMinimap: Raid lockout

### ISSUE THREAD

**Issue by daneras** [renstrom/NeavUI#214]
Hi Team,

is it possible to add a tooltip when you hover over the time on the minimap that show you the active raid- and worldboss lockout (same info as you would see in /raidinfo).

This would be very helpful and i haven't found any standalone addon for this. I also couldn't find the code in ElvUI or TukUI.

Thx for your help :)

Greetings,
Daneras

**Comment by renstrom** [comment]
Fixed in https://github.com/renstrom/NeavUI/pull/232
