### ISSUE TITLE
nChat

### ISSUE THREAD

**Issue by Technojo01** [renstrom/NeavUI#217]
Hey thanks for the updates for 7.1!

It seems something is acting weird now with the font's dropshadows in the chat panel. Looks "off" now. Have a look over there:
[MMOC post](http://www.mmo-champion.com/threads/643236-Post-Your-UI?p=42976586&viewfull=1#post42976586)
[Zorks github](https://github.com/zorker/rothui/commit/b69be719421033b732fcc1053e6524ba3cecf048)

Thanks!

**Comment by renstrom** [comment]
Sounds like a bug on Blizzard's end, so I'll probably just ride it out and hopefully it will be fixed soon™

**Comment by Kkthnx** [comment]
This is indeed a bug blizzard decided to introduce yesterday :D

**Comment by Technojo01** [comment]
But but ... it's ugly !!! ;-)

**Comment by renstrom** [comment]
Apparently this has been hotfixed today according to http://www.wowinterface.com/forums/showthread.php?p=320653#post320653.

**Comment by Technojo01** [comment]
Oh cool! 👍
