### ISSUE TITLE
Druidmana Bar

### ISSUE THREAD

**Issue by pappkartoni** [renstrom/NeavUI#218]
Somehow since the 7.1 patch the alternate mana bar keeps showing for me even when I'm not shapeshifted. I dont't know if this is an issue with oUF, oUF_Neav or even something completely different. Help would be appreciated!

http://imgur.com/gallery/Fubmp <- Screenshot

**Comment by Grimsbain** [comment]
I got on my druid and checked every form in every spec and couldn't get it to break? Does this only happen sometimes and what spec are you?

**Comment by pappkartoni** [comment]
It happens in every spec, also tested it on my shaman.
I tried deleting my Cache, Interface and WTF folders and installing from scratch, the bar is still there.

**Comment by Grimsbain** [comment]
Are you using the oUF version that comes with NeavUI or have you updated it from another source?

**Comment by Grimsbain** [comment]
Hmm, looks like the oUF version included in NeavUI is newer than my version and they renamed the DruidMana element. Will need to updated and release a new version.

**Comment by renstrom** [comment]
Fixed in https://github.com/renstrom/NeavUI/pull/219
