### ISSUE TITLE
Display Bug with latest oUF version

### ISSUE THREAD

**Issue by pappkartoni** [renstrom/NeavUI#222]
I just pulled the latest version of your interface and it ended up bugging out the player and raidframes both.
![wowscrnshot_071917_155026](https://user-images.githubusercontent.com/23081362/28370334-515b4adc-6c9a-11e7-9580-9840dc8a1e7b.jpg)

It doesn't throw any LUA errors in game so I have no idea where to start looking into this. I'm not very familiar with LUA sadly. :/

**Comment by pappkartoni** [comment]
![wowscrnshot_071917_155026](https://user-images.githubusercontent.com/23081362/28370596-f1ff95c4-6c9a-11e7-9cfd-52f7db2f9b22.jpg)

**Comment by Grimsbain** [comment]
They made a bunch of name changes and changed how some things need to be registered with oUF but I think I have things worked out. I just need to merge my changes with the default version of the frames.

**Comment by pappkartoni** [comment]
Oh I see. Will you be able to merge today? I am so used to the raidframes, I can't play with the standard ones anymore. Thanks for your great work!

**Comment by Kkthnx** [comment]
I think this can be closed. Are you sure you are using the most update-to-date versions or everything?

**Comment by renstrom** [comment]
Yes I’m thinking that maybe you’re running the old version of oUF. If you’re using Git, try this:

    git submodule update

**Comment by renstrom** [comment]
Closing. If this is still an issue after making sure you have the correct versions of everything you can re-open.
