### ISSUE TITLE
Stance Bar hiding prevents automatic switching between mainbar and stealth bar.

### ISSUE THREAD

**Issue by jsimpson** [renstrom/NeavUI#237]
https://github.com/renstrom/NeavUI/blob/b74b160570d9c615677b2ea5de1dc2e72958062a/Interface/AddOns/nMainbar/modules/stancebar.lua#L14

I believe that this is preventing the automatic switching between the stealth action bar and the main action bar when moving between stealth and non-stealth when in combat.

On my Rogue (and also tested on my Feral Druid), when in stealth and with the stance bar set to hidden, if I initiate combat from stealth the action bar does not switch over to the main action bar.

**Comment by Grimsbain** [comment]
Woops didn't test it in combat. Should be fixed with #238 I dropped the override on StanceBar_Update() and added a check for combat.

**Comment by renstrom** [comment]
Fixed by #238
