### ISSUE TITLE
Request for MT/MA Windows in oUF_NeavRaid

### ISSUE THREAD

**Issue by thunderchylde** [renstrom/NeavUI#39]
It would be great to have the option to have Main Tank and Main Assist windows

**Comment by Grimsbain** [comment]
I have some minimal main tank/assist frames setup. It only shows the player and no targets at this point. Here is a quick video of them in action.

https://youtu.be/lYWj6lMLBGw

**Comment by Grimsbain** [comment]
Still have more room for improvement but here is what I have so far.

1) Main Tanks/Assist are now all shown in one list with target and target of target frames.
2) The assist frame can be moved independently of the raid frames using the /neavrt slash command.

Unlocking/locking the frames.
https://youtu.be/M4VZQ-ml3s8

The frames in action.
https://youtu.be/T2jnGXCkg3Q

**Comment by Grimsbain** [comment]
The basic main tank/assist frames are now in as of #167. They could be expanded on but they work as is.
