### ISSUE TITLE
Change Wild Mushroom timers for Druids

### ISSUE THREAD

**Issue by renstrom** [renstrom/NeavUI#40]
>I have another question in regard to the unitframes aswell, I play a warrior and druid. and both of them now have abilities of which shows a small circle icons underneath the "Player frame" 
>
for druid, it's to keep track of "shrooms" you will see a circle and a timer under that circle indicating that you have a mushroom down, and if you have 3 mushrooms, you will see 3 circles under YOUR frame. it's with the default WoW and also another unitframe addons, but with NeaV I see that most of my circle is gone, and only a little timer at end of the player frame, which indicate to me that the author don't play druid and he didn't adjust the positioning of the wild mushrooms, if at all possible you take a look at that frame?

**Comment by renstrom** [comment]
![](http://i.imgur.com/2rbmoIT.jpg)

**Comment by renstrom** [comment]
@Grimsbain do you know if this is valid in Legion, does druids even have mushroom timers?

**Comment by Grimsbain** [comment]
@renstrom Just found out that Druids do still have a timer but it isn't for Wild Mushroom. Resto has a spell called Efflorescence that is like the old spell but only heals and they can only ever have one at a time. I just put up a pull request for updates to the totem code for Shamans and Druids.

**Comment by Grimsbain** [comment]
@renstrom Should be fixed so we can close this now.
