### ISSUE TITLE
Is it possible to show focus buffs?

### ISSUE THREAD

**Issue by Erikofdeath** [renstrom/NeavUI#45]
I didn't find this feature in the addon. It will be great to show focus buffs.

**Comment by Grimsbain** [comment]
This is easily done and with the removal of raid buffs in Legion we can show buffs and debuffs without showing a large amount of icons.

**Comment by renstrom** [comment]
Fixed by https://github.com/renstrom/NeavUI/pull/145 and https://github.com/renstrom/NeavUI/pull/146
