### ISSUE TITLE
Tooltip disappear when mousing over certain clickable objects

### ISSUE THREAD

**Issue by Hallonkaka** [renstrom/NeavUI#52]
Below image shows me mousing over a portal and the tooltip shows up for a moment until it goes away. so far I've only seen this happen on items that gives the cogwheel cursor.

I got no other tooltip addon activated.

http://i.imgur.com/k5wA5oj.gif

**Comment by Grimsbain** [comment]
@renstrom We should just remove the disableFade option. It isn't needed and even the config file says that it is known to be buggy.

**Comment by renstrom** [comment]
@Grimsbain removed in bd045ae
