### ISSUE TITLE
Sometimes the nMainbar cannot show the cooldown time

### ISSUE THREAD

**Issue by baoziking** [renstrom/NeavUI#58]
Sometimes the nMainbar cannot show the cooldown time even if i used the system cooldown function.For example,a skill is in cooling,the bar not shown the time,but when i change the mainbar to a second bar,and change back,the time shown.

**Comment by renstrom** [comment]
Closing this since I think it might've been a Blizzard issue. But if it still happens, please leave a comment and I'll re-open.
