### ISSUE TITLE
Is it possible to use the oUF_NeavRaid with the Clique together?

### ISSUE THREAD

**Issue by baoziking** [renstrom/NeavUI#59]
Clique is a simple addon that enables powerful click-casting and hover-casting on your unit frames.So i'm wondering is it possible to use the oUF_NeavRaid with the Clique together?

**Comment by LukeFF** [comment]
I am currently using both addons. works great

**Comment by renstrom** [comment]
Good, then I'm closing this. Probably just a matter of having an up-to-date version of Clique and oUF.
