### ISSUE TITLE
No color change nmainbar Hotkey, Pets not change the font Hotkey

### ISSUE THREAD

**Issue by redstorm12** [renstrom/NeavUI#64]
hi,neal
I really like your addons. thank you always.
There are several bugs.
my nmainbar config.lua setting

showKeybinds = true,
HotKeyText = { 1, 1, 0 },

My settings do not work.
And petbar hotkey font does not change.
Please confirm.

![nmainbar](https://cloud.githubusercontent.com/assets/10217097/5467286/0da4aa6e-8600-11e4-9722-782481db89d5.jpg)

**Comment by Grimsbain** [comment]
@renstrom I have looked into this and all attempts to fix this have failed. It should work because the same code that changes the coloring works for changing the size, font, and outline but the color is being overridden by Blizzard at some point.

**Comment by renstrom** [comment]
Just got another bug report on this issue over at [WoWInterface](http://www.wowinterface.com/downloads/info13981-NeavUI.html#comments).

**Comment by renstrom** [comment]
Fixed by https://github.com/renstrom/NeavUI/pull/172
