### ISSUE TITLE
Is it possible to show only my debuffs on target?

### ISSUE THREAD

**Issue by frankallen** [renstrom/NeavUI#65]
self.Debuffs.onlyShowPlayer = true

Yeah, I know this should fix my request.
But have no idea where to put it in.

**Comment by renstrom** [comment]
You would add it somewhere around [here](https://github.com/renstrom/NeavUI/blob/master/Interface/AddOns/oUF_Neav/core.lua#L1325):

```diff
            self.Auras.numBuffs = config.units.target.numBuffs
            self.Auras.numDebuffs = config.units.target.numDebuffs
            self.Auras.spacing = 4.5
            self.Auras.showStealableBuffs = true
+           self.Auras.onlyShowPlayer = true

            self.Auras.PostUpdateGapIcon = function(self, unit, icon, visibleBuffs)
                icon:Hide()
            end
```

However, this applies to all auras on the target, both buffs *and* debuffs. There's no easy around that at the moment.
