### ISSUE TITLE
Buggy Cooldown-Animation for hidden Icons

### ISSUE THREAD

**Issue by pourmar** [renstrom/NeavUI#66]
Found a new small bug :)

The cooldown animation is visible despite hidden icons. I attached a screenshot for a better understanding :)
You can see the clockwise moving animation for the wild mushroom in the upper left corner (under the player portrait) and the cooldown animation on the right side.

http://imgur.com/qniMXFR

**Comment by renstrom** [comment]
Rumour say this has been fixed by Blizzard in 6.1, can you confirm?
