### ISSUE TITLE
A problem with the unit frame in combat

### ISSUE THREAD

**Issue by redstorm12** [renstrom/NeavUI#67]
I am a warlock user.
I have a pet. But problems arise when the vehicle Quest.
This occurs during the battle..
While trying to vehicle quest,
The problem occurs off at vehicle.

+In combat in vehicle
![ouf2](https://cloud.githubusercontent.com/assets/10217097/6430969/86c0297a-c064-11e4-803c-cff699a0b84c.jpg)
+Down in the vehicle
![ouf](https://cloud.githubusercontent.com/assets/10217097/6431029/71673e1e-c065-11e4-8bd2-755fe4a1825f.jpg)

The above problem often.
interfere with the gameplay.
Please fix this problem..
Thanks to you always.
For me it is the best add-ons NEAV UI!!

**Comment by renstrom** [comment]
Do you have a good place I can go try this out?

**Comment by redstorm12** [comment]
I found a problem with gorgrond quest "Assault on the Pit"
garrison - goblin workshop - "Prototype Mechano-Hog (item)" used during problem.
This problem occurs anywhere.
I tested in "Argent Tournament Ground", but a problem 
You can test go to the Argent Tournament Ground

I am sorry I did not speak English well.
I hope my meaning is well delivered.

**Comment by Grimsbain** [comment]
This is a problem with oUF not NeavUI. It has already been fixed just need pulled into the new version.

https://github.com/haste/oUF/issues/257

The fix posted on the oUF github works on live if you want to update the code yourself.

**Comment by renstrom** [comment]
I'm closing this then, since it's not really something we can do besides wait until the fix makes its way into a oUF release.
