### ISSUE TITLE
The toy box could not be displayed

### ISSUE THREAD

**Issue by baoziking** [renstrom/NeavUI#68]
when upgrade WOW to 6.1,when I clicked the toy box from the nMainbar's menu,the toy box could not be displayed.I noticed that the newest version of the nMainbar just changed the TOC files.I checked the code
"    {
        text = TOY_BOX,
        icon = 'Interface\\MINIMAP\\TRACKING\\Reagents',
        func = function()
            securecall(TogglePetJournal, 3)
        end,
        tooltipTitle = securecall(MicroButtonTooltipText, TOY_BOX, 'TOGGLETOYBOX'),
        tooltipText = TOY_BOX,
        notCheckable = true,
    },"
but I'm not good at coding.-_-#
change the value from 3 to 4,is that OK?

**Comment by renstrom** [comment]
Are you sure you're using the latest version? Because this has already been fixed in https://github.com/renstrom/NeavUI/commit/98734b0ba000611f228ef39277c538397a0e8eee. And I just double checked the release I uploaded to WoWI the other day and it contains these changes as well:

```lua
    {
        text = MOUNTS,
        icon = 'Interface\\MINIMAP\\TRACKING\\StableMaster',
        func = function()
            securecall(ToggleCollectionsJournal, 1)
        end,
        tooltipTitle = securecall(MicroButtonTooltipText, MOUNTS_AND_PETS, 'TOGGLEPETJOURNAL'),
        tooltipText = NEWBIE_TOOLTIP_MOUNTS_AND_PETS,
        notCheckable = true,
    },
    {
        text = TOY_BOX,
        icon = 'Interface\\MINIMAP\\TRACKING\\Reagents',
        func = function()
            securecall(ToggleCollectionsJournal, 3)
        end,
        tooltipTitle = securecall(MicroButtonTooltipText, TOY_BOX, 'TOGGLETOYBOX'),
        tooltipText = TOY_BOX,
        notCheckable = true,
    },
```

**Comment by baoziking** [comment]
sorry,I missed the fixed,problem solved.
