### ISSUE TITLE
Tooltip position fix

### ISSUE THREAD

**Issue by pingumania** [renstrom/NeavUI#69]
Hi, if you change the tooltip position (example: 'TOPLEFT', UIParent, 'TOPLEFT', 30, -30) the tooltip looks weird. 

Here is what i did to fix that: 
``` lua
 hooksecurefunc('GameTooltip_SetDefaultAnchor', function(self, parent)
    if (cfg.showOnMouseover) then
        self:SetOwner(parent, 'ANCHOR_CURSOR')
    else
        self:SetOwner(parent, 'ANCHOR_NONE')
		self:ClearAllPoints() -- Fixes anchoring error
        self:SetPoint(unpack(cfg.position))
    end
end)
```

**Comment by renstrom** [comment]
Fixed in https://github.com/renstrom/NeavUI/commit/5091a4c34efee7551fb82d1c50fdc64e665748d4, thanks! :)
