### ISSUE TITLE
Boss frame

### ISSUE THREAD

**Issue by frankallen** [renstrom/NeavUI#71]
Hello,

Could it be possible to re-organize the boss frames?
I would like to put them horizontal on top of my interface.

Thanks.

**Comment by L3n1n** [comment]
Change the position in the file oUF_Neav/config.lua – 259 line:
```
position = {'TOPRIGHT', UIParent, 'TOPRIGHT', -50, -250},
```

**Comment by renstrom** [comment]
What @L3n1n said.
