### ISSUE TITLE
5 ppl mythic difficulty

### ISSUE THREAD

**Issue by L3n1n** [renstrom/NeavUI#72]
In patch 6.2 was added mythic difficulty for 5 ppl dungeons.
Update pls nMinimap :3

**Comment by renstrom** [comment]
I guess this applies to Timewalker stuff as well...?

**Comment by renstrom** [comment]
Fixed in https://github.com/renstrom/NeavUI/commit/9d2ce7c0555250e09b71c727504eb539a441b0c1 (hopefully, didn't actually test it)
