### ISSUE TITLE
Flexible difficulty bug

### ISSUE THREAD

**Issue by L3n1n** [renstrom/NeavUI#73]
I recently left the [issue](https://github.com/renstrom/NeavUI/issues/72) of a mythical 5ppl difficulty. Then I found another bug with the flexible difficulty of the raid.

The standard frame displays, for example 21H - when 21 people in a raid, and nMinimap shows averages indicators - is it possible to correct?

![flexible difficulty](http://i.imgur.com/R8Ze6wy.jpg)

PS: Sorry for my English =\

**Comment by renstrom** [comment]
Does this fix it? I'm not sure if it updates appropriately when people leave/join the raid though.

https://github.com/renstrom/NeavUI/commit/798d2bd6cf6b5f1163b00d1fc5767aa6f6607db9

**Comment by L3n1n** [comment]
I'm testing now.

**Comment by L3n1n** [comment]
It works, ty!

**Comment by renstrom** [comment]
Great! Did you check if the number was updated when people left and joined?

**Comment by L3n1n** [comment]
Only left.

**Comment by renstrom** [comment]
That's enough I guess :) Closing this now.
