### ISSUE TITLE
nMainbar bug - Out Of Range

### ISSUE THREAD

**Issue by L3n1n** [renstrom/NeavUI#74]
I've found a new bug =\
nMainbar shows «Out Of Range» with a delay – when I choose target hotkeys are highlighted red color, and only then the icons turns red color.

![nMainbar OutOfRange](http://i.imgur.com/yN68jtA.jpg)

I decided to test the addon tullaRange - it displays «Out Of Range» without delay.

**Comment by renstrom** [comment]
>I've found a new bug =\

No worries :P It was been reported before that the out-of-range indicator has been flaky throughout WoD. I just pushed the following change that hopefully dramatically improve the update times for the out-of-range indicator to match Blizzard's indicator.

Please test and report back if it's enough or if I need to tweak even more or just get rid of it altogether and just bundle tullaRange :smile:
 https://github.com/renstrom/NeavUI/commit/414522024ba58a16d787d5e55e217088a4502808

**Comment by L3n1n** [comment]
It works, thank you again!
