### ISSUE TITLE
Taint when trying to cast spells directly from the spellbook.

### ISSUE THREAD

**Issue by frumpymoons** [renstrom/NeavUI#75]
8/21 06:02:04.006  Interface\FrameXML\SpellBookFrame.lua:852 SpellBook_GetSpellBookSlot()
8/21 06:02:04.006  An action was blocked because of taint from nMainbar - CastSpell()
8/21 06:02:04.006      Interface\FrameXML\SpellBookFrame.lua:469 SpellButton_OnClick()
8/21 06:02:04.006      SecondaryProfession3SpellButtonLeft:OnClick()

This only happens if you open the spellbook via the picomenu.

Fix:
``` lua
securecall(ToggleFrame, SpellBookFrame)
``` 
instead of 
``` lua
securecall(ToggleSpellBook, BOOKTYPE_SPELL)
```

**Comment by renstrom** [comment]
Didn't actually verify your fix, but sometimes you just have to wing it. Thanks! :) https://github.com/renstrom/NeavUI/commit/f420efef1936142b4a66c084357ece4e3de96179
