### ISSUE TITLE
PlayerTalentFrame taint when opened with picomenu

### ISSUE THREAD

**Issue by frumpymoons** [renstrom/NeavUI#77]
There is a taint when you try to remove a talent if you open the talents menu via the picomenu.
No problems with glyphs however.

```lua
2x [ADDON_ACTION_FORBIDDEN] AddOn 'nMainbar' tried to call the protected function 'RemoveTalent()'.
!BugGrabber\BugGrabber.lua:589: in function <!BugGrabber\BugGrabber.lua:589>
[C]:: in function 'RemoveTalent'
...rface\Blizzard_TalentUI\Blizzard_TalentUI.lua:39: in function 'OnAccept'
FrameXML\StaticPopup.lua:4082: in function 'StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Comment by frumpymoons** [comment]
Sorry that was actually my fault.

**Comment by renstrom** [comment]
Are you still able to reproduce this? Just tried it and had no problems. Which leads me to believe the taint comes from somewhere else, or Blizzard has done something in some patch.

**Comment by frumpymoons** [comment]
No the issue is gone for me.

**Comment by renstrom** [comment]
Cool, closing this for now then. Can re-open if it happens again.
