### ISSUE TITLE
Tootlip height too high on some units

### ISSUE THREAD

**Issue by frumpymoons** [renstrom/NeavUI#78]
Example:
![Issue](http://i.imgur.com/hxHXNv5.jpg)

There is also the grappling hook in Ashran for example. And I feel like sometimes the height of player tooltips is also a little bit too high.

**Comment by renstrom** [comment]
Have you moved the tooltip position from the lower right corner?

**Comment by frumpymoons** [comment]
Thats my position
"TOPLEFT", UIParent, "TOPLEFT", 18, -15

**Comment by frumpymoons** [comment]
Update:

The problem is that these "objects" are units and the code adds a blank line for the GameTooltipStatusBar but these units don't have one.

**Comment by renstrom** [comment]
Just pushed a fix for this (https://github.com/renstrom/NeavUI/commit/de4c19bd5c3d8e5f5610c0bd44eaf34322a7f88f), thanks for investigating!
