### ISSUE TITLE
Any plans for Legion

### ISSUE THREAD

**Issue by L3n1n** [renstrom/NeavUI#84]
Hello, renstrom!

What are your plans for Legion? You got beta?

**Comment by renstrom** [comment]
Well I plan to at least level my warlock to max level :) Unfortunately I don't have any beta key, so nothing will really happen from my end until then. I guess some issues will also have to be addressed in [oUF](https://github.com/haste/oUF) itself. But I accept issue reports and pull request from people with beta beys who're bold enough to test this UI :)

**Comment by renstrom** [comment]
Just an update, @Grimsbain has been kind enough to provide a bunch of fixes: https://github.com/renstrom/NeavUI/issues?utf8=✓&q=milestone%3ALegion%20

I still don't have a beta key, unfortunately.

**Comment by Grimsbain** [comment]
Except for nPlates (not going to try and update it) everything else is in decent shape at this point. Just need some polish and for Blizzard to work out how everything is going to work with the tracking bars.

http://imgur.com/562hnDI

**Comment by renstrom** [comment]
Yeah, nPlates are a bit of a pain in the ass at the moment (or nameplates in general). They're semi-broken on live as well.

**Comment by frankallen** [comment]
PTR is open now for everyone. If you have time to check the UI (:

**Comment by Grimsbain** [comment]
Is nPower worth updating for Legion? Blizzard has a new frame that does what nPower does and shows important buffs. 

Also oUF_NeavRaid is mostly working but I can't get the AuraWatch code to work. I have tried working on it and did update to a newer function but it doesn't seem to change anything. Whatever is broken is doing so without causing any errors so trying to narrow it down is a bit of a pain.

**Comment by renstrom** [comment]
>Is nPower worth updating for Legion? Blizzard has a new frame that does what nPower does and shows important buffs.

Well I wouldn't put too much effort into it at the moment. For me it was mostly useful for classes like hunters, rogues and warriors with very fluctuating resources.

**Comment by Grimsbain** [comment]
Blizzard has a new interface element built into the nameplates called Personal Resource Display that makes nPower unnecessary. Here is a quick video of the new UI in action on my test Rogue.

https://youtu.be/VeYyfVWTkes

It shows health, resources, and important buff information.

**Comment by renstrom** [comment]
On a related note, I wouldn't mind killing off nPlates too. It's a pain to maintain (especially now with all the extra stuff added) and doesn't really offer much compared to the default nameplates. I think it more or less requires a complete rewrite to get working, and I'm not sure it's worth it.

**Comment by Grimsbain** [comment]
I have looked at the nPlates code and I think you are correct. As far as I can tell all of the nameplate code that Blizzard uses is brand new for this expansion so anything current isn't likely to work with it.
